# Generated by Django 6.1.1 on 2026-09-04 07:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price in INR.', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Price cannot be negative.')])),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Internal cost / COGS in INR.', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Cost price cannot be negative.')])),
                ('inventory_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Inventory quantity cannot be negative.')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='merchants.merchant')),
            ],
            options={
                'ordering': ['merchant', 'name'],
                'indexes': [models.Index(fields=['merchant'], name='product_merchant_idx'), models.Index(fields=['category'], name='product_category_idx'), models.Index(fields=['is_active'], name='product_is_active_idx')],
            },
        ),
    ]
