# Generated by Django 6.1.1 on 2026-09-04 07:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business_name'],
                'indexes': [models.Index(fields=['email'], name='merchant_email_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_margin_percent', models.DecimalField(decimal_places=2, help_text='Minimum acceptable gross-margin % the AI must preserve.', max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Minimum margin cannot be negative.'), django.core.validators.MaxValueValidator(100, message='Minimum margin cannot exceed 100 %.')])),
                ('maximum_discount_percent', models.DecimalField(decimal_places=2, help_text='Maximum discount % the AI is allowed to offer.', max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Discount percentage cannot be negative.'), django.core.validators.MaxValueValidator(100, message='Discount percentage cannot exceed 100 %.')])),
                ('maximum_negotiation_rounds', models.PositiveIntegerField(help_text='Maximum number of back-and-forth negotiation turns allowed.', validators=[django.core.validators.MinValueValidator(1, message='Negotiation rounds must be at least 1.')])),
                ('auto_approval_limit', models.DecimalField(decimal_places=2, help_text='Deal value (in INR) below which the AI may approve automatically without human intervention.', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Auto-approval limit cannot be negative.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Merchant Policy',
                'verbose_name_plural': 'Merchant Policies',
            },
        ),
    ]
