# Generated by Django 6.1.1 on 2026-09-04 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0003_agentnegotiation_agentnegotiationevent'),
        ('merchants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=255)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ORDER_CREATED', 'Order Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_CAPTURED', 'Payment Captured'), ('PAYMENT_FAILED', 'Payment Failed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=32)),
                ('amount_minor_units', models.IntegerField()),
                ('receipt', models.CharField(max_length=255)),
                ('payment_verified', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='merchants.merchant')),
                ('negotiation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='ai.agentnegotiation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
