# Generated by Django 6.1.1 on 2026-09-04 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OFFERED', 'Offered'), ('COUNTER_OFFERED', 'Counter Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=32)),
                ('buyer_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('current_intent', models.JSONField(blank=True, default=dict, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('negotiation_round', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='products.product')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BUYER_MESSAGE', 'Buyer Message'), ('AGENT_MESSAGE', 'Agent Message'), ('OFFER', 'Offer'), ('COUNTER_OFFER', 'Counter Offer'), ('DECISION', 'Decision'), ('ACCEPTANCE', 'Acceptance'), ('REJECTION', 'Rejection'), ('SYSTEM_EVENT', 'System Event')], max_length=32)),
                ('actor', models.CharField(choices=[('BUYER', 'Buyer'), ('AGENT', 'Agent'), ('SYSTEM', 'System')], max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('selected_action', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai.commerceconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
