# Generated by Django 6.1.1 on 2026-09-04 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('merchants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_session_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(default='AI Buyer', max_length=255)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('budget_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preferred_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('walk_away_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('negotiation_enabled', models.BooleanField(default=True)),
                ('maximum_negotiation_rounds', models.IntegerField(default=3)),
                ('strategy', models.CharField(choices=[('VALUE_SEEKER', 'Value Seeker'), ('BALANCED', 'Balanced'), ('FAST_BUYER', 'Fast Buyer')], default='BALANCED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerNegotiationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OFFERED', 'Offered'), ('COUNTER_OFFERED', 'Counter Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=32)),
                ('current_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buyer_last_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('negotiation_round', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ai.buyeragentprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_sessions', to='merchants.merchant')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_sessions', to='products.product')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerNegotiationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BUYER_REQUEST', 'Buyer Request'), ('MERCHANT_OFFER', 'Merchant Offer'), ('BUYER_OFFER', 'Buyer Offer'), ('BUYER_DECISION', 'Buyer Decision'), ('COUNTER_OFFER', 'Counter Offer'), ('ACCEPTANCE', 'Acceptance'), ('REJECTION', 'Rejection'), ('SYSTEM_EVENT', 'System Event')], max_length=32)),
                ('actor', models.CharField(choices=[('BUYER', 'Buyer'), ('MERCHANT', 'Merchant'), ('SYSTEM', 'System')], max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decision', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai.buyernegotiationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
