# Generated by Django 6.1.1 on 2026-09-04 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_buyeragentprofile_buyernegotiationsession_and_more'),
        ('merchants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNegotiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BUYER_TURN', 'Buyer Turn'), ('MERCHANT_TURN', 'Merchant Turn'), ('AGREED', 'Agreed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=32)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buyer_last_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('merchant_last_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('negotiation_round', models.IntegerField(default=0)),
                ('max_rounds', models.IntegerField(default=3)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_ready', models.BooleanField(default=False)),
                ('termination_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_negotiations', to='ai.buyeragentprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_negotiations', to='merchants.merchant')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_negotiations', to='products.product')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentNegotiationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=0)),
                ('actor', models.CharField(choices=[('AI_BUYER', 'AI Buyer'), ('AI_MERCHANT', 'AI Merchant'), ('SYSTEM', 'System')], max_length=32)),
                ('event_type', models.CharField(choices=[('NEGOTIATION_STARTED', 'Negotiation Started'), ('PRODUCT_SELECTED', 'Product Selected'), ('MERCHANT_OFFER', 'Merchant Offer'), ('BUYER_COUNTER', 'Buyer Counter'), ('BUYER_ACCEPT', 'Buyer Accept'), ('BUYER_REJECT', 'Buyer Reject'), ('MERCHANT_COUNTER', 'Merchant Counter'), ('MERCHANT_ACCEPT', 'Merchant Accept'), ('MERCHANT_REJECT', 'Merchant Reject'), ('AGREEMENT_REACHED', 'Agreement Reached'), ('NEGOTIATION_ENDED', 'Negotiation Ended'), ('SYSTEM_EVENT', 'System Event')], max_length=32)),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decision', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai.agentnegotiation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
